### ISSUE TITLE
Did you use the GAN structure？

### ISSUE THREAD

**Issue by jackfrost168** [jmiller656/EDSR-Tensorflow#51]

**Comment by jmiller656** [comment]
No, this uses resnet-style layers and does pixel shuffling rather than convolution to upscale

**Comment by jackfrost168** [comment]
Thank you！

**Comment by jackfrost168** [comment]
And I have another question. The EDSR's paper said it is based on SRResNet architecture which is used gan architecture. EDSR is removing unnecessary modules. In SRResNet，it use pixel shuffling too. From my point of view，EDSR should also use the gan architecture because it is based on SRResNet as the paper said，am I right？

**Comment by jmiller656** [comment]
Just because it takes inspiration from SRResNet, does not need it should use the same architecture. There isn't necessarily a "right answer" in terms of NN architectures as far as I'm aware. 

It's also worth making clear: I am not the person who wrote the EDSR paper. I just happen to provide a TensorFlow implementation of their work on Github.

**Comment by jackfrost168** [comment]
Thank you for your replying！
